### ISSUE TITLE
what is topomap pos parameter?

### ISSUE THREAD

**Issue by DunkHimYo** [Nikeshbajaj/Notebooks#1]
i've seen this sp.eeg.TopoMap method But example is not init pos parameter how can I use this?

**Comment by Nikeshbajaj** [comment]
import spkit as sp
Yes, indeed, for 14-channel, you can use it like 
pos = sp.eeg.pos
ch_names = sp.eeg.ch_names

However, for different channels and a few selected channels, you can extract pos as

ch_names = ['AF3','F7','F3','FC5','T7','P7','O1','O2','P8','T8','FC6','F4','F8','AF4']
pos, ch1 = sp.eeg.s1020_get_epos2d_(ch_names, reorder=False)
